export const MOVIES_LIST = [
    "Star Wars: Episode VII - The Force Awakens",
    "Avengers: Endgame",
    "Spider-Man: No Way Home",
    "Avatar",
    "Top Gun: Maverick",
    "Black Panther",
    "Avatar: The Way of Water",
    "Avengers: Infinity War",
    "Titanic",
    "Jurassic World",
    "Barbie",
    "The Avengers",
    "Star Wars: Episode VIII - The Last Jedi",
    "Incredibles 2",
    "The Super Mario Bros. Movie",
    "The Lion King",
    "The Dark Knight",
    "Rogue One: A Star Wars Story",
    "Star Wars: Episode IX - The Rise of Skywalker",
    "Beauty and the Beast",
    "Finding Dory",
    "Frozen II",
    "Star Wars: Episode I - The Phantom Menace",
    "Star Wars",
    "Avengers: Age of Ultron",
    "Black Panther: Wakanda Forever",
    "The Dark Knight Rises",
    "Shrek 2",
    "E.T. the Extra-Terrestrial",
    "Toy Story 4",
    "Captain Marvel",
    "The Hunger Games: Catching Fire",
    "Pirates of the Caribbean: Dead Man's Chest",
    "The Lion King",
    "Jurassic World: Fallen Kingdom",
    "Toy Story 3",
    "Wonder Woman",
    "Doctor Strange in the Multiverse of Madness",
    "Iron Man 3",
    "Captain America: Civil War",
    "The Hunger Games",
    "Spider-Man",
    "Jurassic Park",
    "Jumanji: Welcome to the Jungle",
    "Transformers: Revenge of the Fallen",
    "Frozen",
    "Spider-Man: Far from Home",
    "Guardians of the Galaxy Vol. 2",
    "Spider-Man: Across the Spider-Verse",
    "Harry Potter and the Deathly Hallows: Part 2",
    "Finding Nemo",
    "Star Wars: Episode III - Revenge of the Sith",
    "The Lord of the Rings: The Return of the King",
    "Jurassic World Dominion",
    "Spider-Man 2",
    "Minions: The Rise of Gru",
    "The Batman",
    "The Secret Life of Pets",
    "Despicable Me 2",
    "The Jungle Book",
    "Deadpool",
    "Guardians of the Galaxy Vol. 3",
    "Inside Out",
    "Aladdin",
    "Furious 7",
    "Transformers: Dark of the Moon",
    "American Sniper",
    "Thor: Love and Thunder",
    "The Lord of the Rings: The Two Towers",
    "Zootopia",
    "Spider-Man 3",
    "The Hunger Games: Mockingjay - Part 1",
    "Minions",
    "Joker",
    "Aquaman",
    "Spider-Man: Homecoming",
    "Alice in Wonderland",
    "Guardians of the Galaxy",
    "Forrest Gump",
    "Batman v Superman: Dawn of Justice",
    "Oppenheimer",
    "It",
    "Suicide Squad",
    "Deadpool 2",
    "Shrek the Third",
    "Jumanji: The Next Level",
    "Transformers",
    "Iron Man",
    "Harry Potter and the Sorcerer's Stone",
    "Indiana Jones and the Kingdom of the Crystal Skull",
    "Star Wars: Episode VI - Return of the Jedi",
    "The Lord of the Rings: The Fellowship of the Ring",
    "Thor: Ragnarok",
    "Iron Man 2",
    "Star Wars: Episode II - Attack of the Clones",
    "Pirates of the Caribbean: At World's End",
    "Independence Day",
    "Pirates of the Caribbean: The Curse of the Black Pearl",
    "Skyfall",
    "The Hobbit: An Unexpected Journey",
    "Harry Potter and the Half-Blood Prince",
    "The Twilight Saga: Eclipse",
    "The Little Mermaid",
    "The Twilight Saga: New Moon",
    "Harry Potter and the Deathly Hallows: Part 1",
    "The Sixth Sense",
    "Up",
    "Star Wars: Episode V - The Empire Strikes Back",
    "Inception",
    "Harry Potter and the Order of the Phoenix",
    "The Twilight Saga: Breaking Dawn - Part 2",
    "The Chronicles of Narnia: The Lion, the Witch and the Wardrobe",
    "Man of Steel",
    "Monsters, Inc.",
    "Harry Potter and the Goblet of Fire",
    "Home Alone",
    "The Hunger Games: Mockingjay - Part 2",
    "The Matrix Reloaded",
    "The Twilight Saga: Breaking Dawn - Part 1",
    "Dune: Part Two",
    "The Hangover",
    "Gravity",
    "The Grinch",
    "Sing",
    "Monsters University",
    "Shrek",
    "Jaws",
    "Despicable Me 3",
    "Harry Potter and the Chamber of Secrets",
    "The Amazing Spider-Man",
    "The Incredibles",
    "How the Grinch Stole Christmas",
    "Captain America: The Winter Soldier",
    "The Hobbit: The Desolation of Smaug",
    "The Lego Movie",
    "Star Trek",
    "I Am Legend",
    "The Blind Side",
    "The Hobbit: The Battle of the Five Armies",
    "The Hangover Part II",
    "Despicable Me",
    "Batman",
    "Night at the Museum",
    "Men in Black",
    "Harry Potter and the Prisoner of Azkaban",
    "Moana",
    "Raiders of the Lost Ark",
    "Toy Story 2",
    "Transformers: Age of Extinction",
    "Cars",
    "Ghostbusters",
    "Bruce Almighty",
    "Twister",
    "My Big Fat Greek Wedding",
    "Maleficent",
    "Pirates of the Caribbean: On Stranger Tides",
    "Shrek Forever After",
    "Fast & Furious 6",
    "Brave",
    "Oz the Great and Powerful",
    "Beverly Hills Cop",
    "X-Men: The Last Stand",
    "War of the Worlds",
    "Fantastic Beasts and Where to Find Them",
    "X-Men: Days of Future Past",
    "Cast Away",
    "The Exorcist",
    "Doctor Strange",
    "The Lost World: Jurassic Park",
    "Justice League",
    "Star Trek Into Darkness",
    "The Martian",
    "Signs",
    "Hancock",
    "The Bourne Ultimatum",
    "Logan",
    "Rush Hour 2",
    "The Fate of the Furious",
    "Shang-Chi and the Legend of the Ten Rings",
    "WALL·E",
    "Toy Story",
    "Big Hero 6",
    "Mission: Impossible - Fallout",
    "National Treasure: Book of Secrets",
    "Alvin and the Chipmunks: The Squeakquel",
    "Mrs. Doubtfire",
    "Beauty and the Beast",
    "Ted",
    "Wonka",
    "King Kong",
    "Ghost",
    "How to Train Your Dragon",
    "The Da Vinci Code",
    "Aladdin",
    "Alvin and the Chipmunks",
    "Saving Private Ryan",
    "Bohemian Rhapsody",
    "Ant-Man and the Wasp",
    "Madagascar 3: Europe's Most Wanted",
    "Kung Fu Panda",
    "Mission: Impossible II",
    "A Star Is Born",
    "X2",
    "Ant-Man and the Wasp: Quantumania",
    "The Lorax",
    "Back to the Future",
    "Solo: A Star Wars Story",
    "Venom: Let There Be Carnage",
    "Venom",
    "Austin Powers in Goldmember",
    "It Chapter Two",
    "300",
    "Coco",
    "Fast Five",
    "Mission: Impossible - Ghost Protocol",
    "Wedding Crashers",
    "Sherlock Holmes",
    "Dawn of the Planet of the Apes",
    "Batman Begins",
    "Charlie and the Chocolate Factory",
    "Ratatouille",
    "Thor: The Dark World",
    "Bad Boys for Life",
    "Austin Powers: The Spy Who Shagged Me",
    "Terminator 2: Judgment Day",
    "The Amazing Spider-Man 2",
    "World War Z",
    "The Mummy Returns",
    "Armageddon",
    "Cinderella",
    "Ralph Breaks the Internet",
    "Gone with the Wind",
    "Tangled",
    "Godzilla",
    "Superman Returns",
    "Spectre",
    "Pearl Harbor",
    "Monsters vs. Aliens",
    "Happy Feet",
    "Indiana Jones and the Last Crusade",
    "Ice Age: Dawn of the Dinosaurs",
    "Ice Age: The Meltdown",
    "Mission: Impossible - Rogue Nation",
    "Twilight",
    "Men in Black II",
    "Madagascar",
    "22 Jump Street",
    "Cars 2",
    "Teenage Mutant Ninja Turtles",
    "Sonic the Hedgehog 2",
    "Spider-Man: Into the Spider-Verse",
    "Grease",
    "Dunkirk",
    "The Polar Express",
    "Wreck-It Ralph",
    "A Quiet Place",
    "Interstellar",
    "Gladiator",
    "The Croods",
    "John Wick: Chapter 4",
    "Sherlock Holmes: A Game of Shadows",
    "The Day After Tomorrow",
    "Mr. & Mrs. Smith",
    "Puss in Boots: The Last Wish",
    "Snow White and the Seven Dwarfs",
    "Pitch Perfect 2",
    "Dances with Wolves",
    "Batman Forever",
    "The Fugitive",
    "Black Widow",
    "The Revenant",
    "Ocean's Eleven",
    "The Simpsons Movie",
    "What Women Want",
    "The Perfect Storm",
    "Lincoln",
    "Kung Fu Panda 4",
    "Liar Liar",
    "Jurassic Park III",
    "Thor",
    "Mission: Impossible",
    "Taylor Swift: The Eras Tour",
    "Top Gun",
    "Ant-Man",
    "Planet of the Apes",
    "Madagascar: Escape 2 Africa",
    "X-Men Origins: Wolverine",
    "Indiana Jones and the Temple of Doom",
    "Hitch",
    "Men in Black 3",
    "Pretty Woman",
    "Elf",
    "Home",
    "Night at the Museum: Battle of the Smithsonian",
    "Tootsie",
    "How to Train Your Dragon 2",
    "Rise of the Planet of the Apes",
    "Captain America: The First Avenger",
    "The Karate Kid",
    "There's Something About Mary",
    "Ice Age",
    "The Bourne Supremacy",
    "Get Out",
    "The Lego Batman Movie",
    "Us",
    "The Boss Baby",
    "Crazy Rich Asians",
    "Crocodile Dundee",
    "Indiana Jones and the Dial of Destiny",
    "Godzilla x Kong: The New Empire",
    "The Greatest Showman",
    "Fast & Furious Presents: Hobbs & Shaw",
    "Apollo 13",
    "Home Alone 2: Lost in New York",
    "National Treasure",
    "F9: The Fast Saga",
    "Air Force One",
    "Rain Man",
    "Pirates of the Caribbean: Dead Men Tell No Tales",
    "Mission: Impossible - Dead Reckoning Part One",
    "The Matrix",
    "Tron: Legacy",
    "Mary Poppins Returns",
    "True Grit",
    "Tarzan",
    "John Wick: Chapter 3 - Parabellum",
    "A Beautiful Mind",
    "Chicago",
    "The Help",
    "Hotel Transylvania 2",
    "Hidden Figures",
    "Bridesmaids",
    "Quantum of Solace",
    "Wild Hogs",
    "Black Adam",
    "Kong: Skull Island",
    "Three Men and a Baby",
    "Gone Girl",
    "Hotel Transylvania 3: Summer Vacation",
    "Casino Royale",
    "The Hunger Games: The Ballad of Songbirds & Snakes",
    "Meet the Parents",
    "2012",
    "Robin Hood: Prince of Thieves",
    "Knives Out",
    "Kung Fu Panda 2",
    "Hannibal",
    "Eternals",
    "Catch Me If You Can",
    "The Proposal",
    "The Pursuit of Happyness",
    "Big Daddy",
    "Clash of the Titans",
    "The SpongeBob Movie: Sponge Out of Water",
    "Batman Returns",
    "Django Unchained",
    "A Bug's Life",
    "Sing 2",
    "Jason Bourne",
    "Grown Ups",
    "The Waterboy",
    "Ice Age: Continental Drift",
    "Straight Outta Compton",
    "How to Train Your Dragon: The Hidden World",
    "Die Another Day",
    "No Time to Die",
    "Shark Tale",
    "A Quiet Place Part II",
    "The Heat",
    "Fantastic Beasts: The Crimes of Grindelwald",
    "Halloween",
    "The Sound of Music",
    "1917",
    "The Secret Life of Pets 2",
    "Star Trek Beyond",
    "The Firm",
    "The Longest Yard",
    "X-Men",
    "Transformers: Rise of the Beasts",
    "Scary Movie",
    "Who Framed Roger Rabbit",
    "Creed III",
    "The Sting",
    "The Mummy",
    "What Lies Beneath",
    "X-Men: Apocalypse",
    "Snow White and the Huntsman",
    "San Andreas",
    "Fast & Furious",
    "Over the Hedge",
    "Fantastic Four",
    "Horton Hears a Who!",
    "Elemental",
    "Mad Max: Fury Road",
    "Trolls",
    "Jerry Maguire",
    "Beverly Hills Cop II",
    "Gremlins",
    "Scooby-Doo",
    "Cars 3",
    "Sex and the City",
    "Runaway Bride",
    "La La Land",
    "Elvis",
    "Divergent",
    "Rambo: First Blood Part II",
    "We're the Millers",
    "Terminator 3: Rise of the Machines",
    "Daddy's Home",
    "G.I. Joe: The Rise of Cobra",
    "Neighbors",
    "American Hustle",
    "Puss in Boots",
    "Les Misérables",
    "Sonic the Hedgehog",
    "Knocked Up",
    "Uncharted",
    "As Good as It Gets",
    "Megamind",
    "Hotel Transylvania",
    "Talladega Nights: The Ballad of Ricky Bobby",
    "Gran Torino",
    "Lethal Weapon 2",
    "War for the Planet of the Apes",
    "X-Men: First Class",
    "Paul Blart: Mall Cop",
    "True Lies",
    "Fast X",
    "Lilo & Stitch",
    "The Santa Clause",
    "The Meg",
    "American Pie 2",
    "Taken",
    "One Hundred and One Dalmatians",
    "The Great Gatsby",
    "I, Robot",
    "The Fast and the Furious",
    "Lethal Weapon 3",
    "Mamma Mia!",
    "Pokémon: Detective Pikachu",
    "Doctor Dolittle",
    "Rio",
    "Kung Fu Panda 3",
    "Juno",
    "Marley & Me",
    "The Smurfs",
    "Once Upon a Time... in Hollywood",
    "xXx",
    "The Jungle Book",
    "The Chronicles of Narnia: Prince Caspian",
    "National Lampoon's Animal House",
    "Pocahontas",
    "A Few Good Men",
    "Slumdog Millionaire",
    "Rush Hour",
    "The Blair Witch Project",
    "Shazam!",
    "Deep Impact",
    "Ocean's Eight",
    "Rush Hour 3",
    "Look Who's Talking",
    "Stuart Little",
    "Taken 2",
    "Sister Act",
    "The Matrix Revolutions",
    "The Santa Clause 2",
    "The King's Speech",
    "Cheaper by the Dozen",
    "Bad Boys II",
    "Platoon",
    "21 Jump Street",
    "Good Will Hunting",
    "Split",
    "A Christmas Carol",
    "Dinosaur",
    "Ready Player One",
    "The Conjuring",
    "Click",
    "Five Nights at Freddy's",
    "The Green Mile",
    "Ransom",
    "The Godfather",
    "Godzilla",
    "101 Dalmatians",
    "Argo",
    "Anger Management",
    "Chicken Little",
    "Teenage Mutant Ninja Turtles",
    "Close Encounters of the Third Kind",
    "Patch Adams",
    "Ride Along",
    "The Incredible Hulk",
    "Live Free or Die Hard",
    "Wanted",
    "Identity Thief",
    "Superman",
    "The Rock",
    "Mission: Impossible III",
    "Grown Ups 2",
    "Troy",
    "Angels & Demons",
    "Alvin and the Chipmunks: Chipwrecked",
    "Bringing Down the House",
    "The Wolverine",
    "Wonder",
    "The Departed",
    "Hulk",
    "Silver Linings Playbook",
    "Minority Report",
    "Fantastic Four: Rise of the Silver Surfer",
    "The Last Airbender",
    "Rio 2",
    "Lara Croft: Tomb Raider",
    "The Silence of the Lambs",
    "Honey, I Shrunk the Kids",
    "The Flintstones",
    "Lethal Weapon 4",
    "Get Smart",
    "The Divergent Series: Insurgent",
    "The Peanuts Movie",
    "Transformers: The Last Knight",
    "American Gangster",
    "American Beauty",
    "An Officer and a Gentleman",
    "Ghostbusters: Afterlife",
    "The Ring",
    "The Nutty Professor",
    "Crouching Tiger, Hidden Dragon",
    "Borat",
    "Ghostbusters",
    "Kingsman: The Secret Service",
    "Robots",
    "Coming to America",
    "Shutter Island",
    "Into the Woods",
    "Rocky IV",
    "Enchanted",
    "The Curious Case of Benjamin Button",
    "Central Intelligence",
    "Anchorman 2: The Legend Continues",
    "Migration",
    "Sweet Home Alabama",
    "Bumblebee",
    "Dumb and Dumber",
    "2 Fast 2 Furious",
    "My Best Friend's Wedding",
    "Super 8",
    "The World Is Not Enough",
    "Sleepless in Seattle",
    "Smokey and the Bandit",
    "Lucy",
    "The Legend of Tarzan",
    "Bee Movie",
    "Prometheus",
    "Safe House",
    "Mr. Deeds",
    "The Truman Show",
    "Erin Brockovich",
    "Ocean's Twelve",
    "Terminator Salvation",
    "Charlie's Angels",
    "Tomorrow Never Dies",
    "Lone Survivor",
    "Sully",
    "Rocky III",
    "The Vow",
    "Life of Pi",
    "The Fault in Our Stars",
    "Cloudy with a Chance of Meatballs",
    "The Devil Wears Prada",
    "Something's Gotta Give",
    "Aquaman and the Lost Kingdom",
    "Traffic",
    "The Birdcage",
    "City Slickers",
    "Good Morning, Vietnam",
    "Rango",
    "Nutty Professor II: The Klumps",
    "Nope",
    "The Good Dinosaur",
    "G.I. Joe: Retaliation",
    "Clear and Present Danger",
    "The Bodyguard",
    "The Hunt for Red October",
    "Wayne's World",
    "The Bourne Identity",
    "Free Guy",
    "Superbad",
    "Speed",
    "50 First Dates",
    "Mamma Mia! Here We Go Again",
    "Mulan",
    "Seabiscuit",
    "Van Helsing",
    "Four Christmases",
    "The Mask",
    "Cloudy with a Chance of Meatballs 2",
    "Hook",
    "Blazing Saddles",
    "Walk the Line",
    "G-Force",
    "Total Recall",
    "On Golden Pond",
    "The Other Guys",
    "Back to the Future Part II",
    "Hairspray",
    "The Sum of All Fears",
    "The Break-Up",
    "A Series of Unfortunate Events",
    "Teenage Mutant Ninja Turtles: Mutant Mayhem",
    "Blades of Glory",
    "Salt",
    "Lightyear",
    "Now You See Me",
    "Ford v Ferrari",
    "Big Momma's House",
    "Die Hard 2",
    "Horrible Bosses",
    "The Nun",
    "Rocky",
    "Jackass 3D",
    "Ocean's Thirteen",
    "Jungle Cruise",
    "S.W.A.T.",
    "The Wolf of Wall Street",
    "8 Mile",
    "Double Jeopardy",
    "The Butler",
    "Green Lantern",
    "Notting Hill",
    "The Towering Inferno",
    "You've Got Mail",
    "Ghost Rider",
    "Remember the Titans",
    "Creed II",
    "District 9",
    "Unbroken",
    "Peter Rabbit",
    "Big",
    "Girls Trip",
    "The Karate Kid Part II",
    "American Graffiti",
    "Dumbo",
    "Dodgeball: A True Underdog Story",
    "The Village",
    "Bolt",
    "Maleficent: Mistress of Evil",
    "Wild Wild West",
    "Magic Mike",
    "Night at the Museum: Secret of the Tomb",
    "The Addams Family",
    "The Patriot",
    "Bad Moms",
    "The Bourne Legacy",
    "The Pacifier",
    "Dr. Dolittle 2",
    "The Rocky Horror Picture Show",
    "It's Complicated",
    "Spy Kids",
    "Ghostbusters II",
    "Face/Off",
    "The Hangover Part III",
    "Twins",
    "Spy Kids 3: Game Over",
    "Doctor Zhivago",
    "Enemy of the State",
    "The Little Mermaid",
    "Mr. Peabody & Sherman",
    "Porky's",
    "The Last Samurai",
    "Glass",
    "Spy",
    "Valentine's Day",
    "Tropic Thunder",
    "Godzilla: King of the Monsters",
    "The Grudge",
    "Fun with Dick and Jane",
    "Freaky Friday",
    "Trainwreck",
    "Bedtime Stories",
    "Scary Movie 3",
    "Creed",
    "Star Trek IV: The Voyage Home",
    "The 40-Year-Old Virgin",
    "Crocodile Dundee II",
    "Couples Retreat",
    "One Flew Over the Cuckoo's Nest",
    "Dune",
    "A Time to Kill",
    "Black Hawk Down",
    "Hop",
    "Terms of Endearment",
    "Ace Ventura: When Nature Calls",
    "The Upside",
    "The Princess Diaries",
    "Superman II",
    "Scream VI",
    "The Flash",
    "Little Women",
    "Pulp Fiction",
    "Paranormal Activity",
    "Baby Driver",
    "A League of Their Own",
    "Epic",
    "Watchmen",
    "The Angry Birds Movie",
    "Batman & Robin",
    "Captain Phillips",
    "Black Swan",
    "Analyze This",
    "Chicken Run",
    "Miss Congeniality",
    "Indecent Proposal",
    "Driving Miss Daisy",
    "300: Rise of an Empire",
    "Love Story",
    "GoldenEye",
    "Kramer vs. Kramer",
    "The Italian Job",
    "The Lego Movie 2: The Second Part",
    "Smile",
    "How to Lose a Guy in 10 Days",
    "The First Wives Club",
    "The Lost City",
    "Robin Hood",
    "Interview with the Vampire",
    "George of the Jungle",
    "Hustlers",
    "The Graduate",
    "Pitch Perfect 3",
    "Phenomenon",
    "American Wedding",
    "Road to Perdition",
    "The Princess and the Frog",
    "The Chronicles of Narnia: The Voyage of the Dawn Treader",
    "Daddy Day Care",
    "Ghostbusters: Frozen Empire",
    "Daddy's Home 2",
    "Paranormal Activity 3",
    "Journey 2: The Mysterious Island",
    "The Mule",
    "Dick Tracy",
    "Rise of the Guardians",
    "Bullet Train",
    "Dreamgirls",
    "9 to 5",
    "Independence Day: Resurgence",
    "The Expendables",
    "Scream",
    "Just Go with It",
    "Trolls Band Together",
    "Murder on the Orient Express",
    "The General's Daughter",
    "The Aviator",
    "American Pie",
    "Daredevil",
    "The Conjuring 2",
    "The Girl with the Dragon Tattoo",
    "The Mummy: Tomb of the Dragon Emperor",
    "The Maze Runner",
    "In the Line of Fire",
    "Butch Cassidy and the Sundance Kid",
    "Mary Poppins",
    "Bambi",
    "Annabelle: Creation",
    "The Equalizer 2",
    "Jackass Presents: Bad Grandpa",
    "Pacific Rim",
    "Journey to the Center of the Earth",
    "Gone in 60 Seconds",
    "Maverick",
    "Sleeping with the Enemy",
    "The Equalizer",
    "This Is the End",
    "Eagle Eye",
    "The Prince of Egypt",
    "Scream 2",
    "Stir Crazy",
    "Eraser",
    "Noah",
    "Unforgiven",
    "The Cat in the Hat",
    "Con Air",
    "Sleepy Hollow",
    "Rampage",
    "Collateral",
    "Contact",
    "Godzilla vs. Kong",
    "Charlie's Angels: Full Throttle",
    "The Pelican Brief",
    "The Addams Family",
    "Vanilla Sky",
    "Arrival",
    "Due Date",
    "Jumanji",
    "The Rugrats Movie",
    "Million Dollar Baby",
    "Airport",
    "A Wrinkle in Time",
    "Step Brothers",
    "Evan Almighty",
    "Casper",
    "Shakespeare in Love",
    "Bad Teacher",
    "Yogi Bear",
    "Cowboys & Aliens",
    "Kingsman: The Golden Circle",
    "Edge of Tomorrow",
    "The Hunchback of Notre Dame",
    "Se7en",
    "Parenthood",
    "You Don't Mess with the Zohan",
    "Passengers",
    "Die Hard with a Vengeance",
    "Gnomeo & Juliet",
    "Christopher Robin",
    "Hercules",
    "Olympus Has Fallen",
    "The Green Hornet",
    "Date Night",
    "The Color Purple",
    "Meet the Robinsons",
    "Yes Man",
    "Sausage Party",
    "The Bad Guys",
    "Inspector Gadget",
    "Public Enemies",
    "The Social Network",
    "Bob Marley: One Love",
    "Downton Abbey",
    "The Others",
    "Legally Blonde",
    "Panic Room",
    "Rocketman",
    "Encanto",
    "Apocalypse Now",
    "Dead Poets Society",
    "Fantastic Beasts: The Secrets of Dumbledore",
    "Zero Dark Thirty",
    "Norbit",
    "Cold Mountain",
    "Arthur",
    "Sex and the City 2",
    "Michael",
    "The Princess Diaries 2: Royal Engagement",
    "M3GAN",
    "42",
    "Unbreakable",
    "The Book of Eli",
    "10,000 BC",
    "Beverly Hills Chihuahua",
    "Saturday Night Fever",
    "Julie & Julia",
    "The Mask of Zorro",
    "Maid in Manhattan",
    "He's Just Not That Into You",
    "Master and Commander: The Far Side of the World",
    "Flight",
    "DC League of Super-Pets",
    "The Fighter",
    "America's Sweethearts",
    "Lady and the Tramp",
    "The Bucket List",
    "Tomorrowland",
    "The Magnificent Seven",
    "Cats & Dogs",
    "Space Station 3D",
    "Two Weeks Notice",
    "Dungeons & Dragons: Honor Among Thieves",
    "Red Dragon",
    "Cinderella",
    "When Harry Met Sally...",
    "Elysium",
    "Flubber",
    "Flashdance",
    "The Equalizer 3",
    "The Town",
    "Non-Stop",
    "The Client",
    "Blade Runner 2049",
    "John Wick: Chapter 2",
    "Star Trek: First Contact",
    "Halloween Kills",
    "Think Like a Man",
    "Kindergarten Cop",
    "Heaven Is for Real",
    "The Haunting",
    "Crimson Tide",
    "Back to School",
    "Ride Along 2",
    "Stepmom",
    "The Imitation Game",
    "The Karate Kid",
    "Save the Last Dance",
    "The Scorpion King",
    "Prince of Persia: The Sands of Time",
    "Antz",
    "Scary Movie 4",
    "The Game Plan",
    "Space Jam",
    "Me, Myself & Irene",
    "High School Musical 3: Senior Year",
    "Madea Goes to Jail",
    "Space Cowboys",
    "Get Hard",
    "Trading Places",
    "RED",
    "Planes",
    "Where the Crawdads Sing",
    "Legally Blonde 2: Red, White & Blonde",
    "Mystic River",
    "The Black Phone",
    "Terminator Genisys",
    "Flightplan",
    "The Emperor's New Groove",
    "Father of the Bride",
    "The Lone Ranger",
    "Taken 3",
    "Don't Breathe",
    "Scream 3",
    "Oblivion",
    "The Ugly Truth",
    "Percy Jackson & the Olympians: The Lightning Thief",
    "Failure to Launch",
    "The Muppets",
    "Inside Man",
    "Anyone But You",
    "Back to the Future Part III",
    "Waterworld",
    "Starsky & Hutch",
    "Along Came Polly",
    "The Hand That Rocks the Cradle",
    "Entrapment",
    "The Nightmare Before Christmas",
    "Peter Pan",
    "Pineapple Express",
    "Miss Peregrine's Home for Peculiar Children",
    "Everest",
    "Out of Africa",
    "Sisters",
    "Saw II",
    "The Naked Gun 2½: The Smell of Fear",
    "The Campaign",
    "The War of the Roses",
    "The Amityville Horror",
    "Presumed Innocent",
    "Young Frankenstein",
    "The Nun II",
    "The Accountant",
    "Dumb and Dumber To",
    "Cruella",
    "The Emoji Movie",
    "Mean Girls",
    "Annie",
    "Die Hard",
    "Alvin and the Chipmunks: The Road Chip",
    "Spy Kids 2: Island of Lost Dreams",
    "Alita: Battle Angel",
    "Fury",
    "Pokémon: The First Movie - Mewtwo Strikes Back",
    "Real Steel",
    "The SpongeBob SquarePants Movie",
    "Power Rangers",
    "Brother Bear",
    "Stripes",
    "Anchorman: The Legend of Ron Burgundy",
    "Every Which Way But Loose",
    "Rocky II",
    "Aliens",
    "Open Season",
    "Green Book",
    "The Expendables 2",
    "Dangerous Minds",
    "Paranormal Activity 2",
    "Steel Magnolias",
    "The Poseidon Adventure",
    "Tammy",
    "The Marvels",
    "The Santa Clause 3: The Escape Clause",
    "Ferdinand",
    "Crazy, Stupid, Love",
    "Annabelle",
    "Pinocchio",
    "Scooby-Doo 2: Monsters Unleashed",
    "Birds of Prey",
    "Atlantis: The Lost Empire",
    "Cliffhanger",
    "Moulin Rouge",
    "Cats",
    "The Wizard of Oz",
    "Paddington",
    "The NeverEnding Story",
    "The Breakfast Club",
    "The Crow",
    "Predator",
    "Poltergeist",
    "Citizen Kane",
    "The Shining",
    "Gladiator"
]