export const MOVIES_LIST = [
    "12 Angry Men",
    "50 First Dates",
    "A Nightmare on Elm Street",
    "Alien",
    "Anchorman",
    "Annabelle",
    "Armageddon",
    "Austin Powers",
    "Avatar",
    "Back to the Future",
    "Bambi",
    "Barbie",
    "Batman",
    "Beauty and the Beast",
    "Black Panther",
    "Blade Runner",
    "Braveheart",
    "Captain America",
    "Cars",
    "Cinderella",
    "Citizen Kane",
    "Die Hard",
    "Dumbo",
    "E.T. the Extra Terrestrial",
    "Fight Club",
    "Finding Nemo",
    "Forrest Gump",
    "Friday the 13th",
    "Frozen",
    "Ghost",
    "Ghostbusters",
    "Gladiator",
    "Godzilla",
    "Gravity",
    "Groundhog Day",
    "Halloween",
    "Ice Age",
    "Inception",
    "Independence Day",
    "Interstellar",
    "Iron Man",
    "It's a Wonderful Life",
    "Jaws",
    "John Wick",
    "Jumanji",
    "Jurassic Park",
    "Kill Bill",
    "King Kong",
    "Life of Pi",
    "Love Actually",
    "Mad Max: Fury Road",
    "Memento",
    "Men in Black",
    "Minions",
    "Moulin Rouge",
    "My Neighbour Totoro",
    "Night at the Museum",
    "One Flew Over the Cuckoo's Nest",
    "Parasite",
    "Pirates of the Carribean",
    "Pitch Perfect",
    "Psycho",
    "Pulp Fiction",
    "Raiders of the Lost Ark",
    "Ratatouille",
    "Ready Player One",
    "Rocky",
    "Saving Private Ryan",
    "Shrek",
    "Sing",
    "Sleepless in Seattle",
    "Snow White and the Seven Dwarves",
    "Speed",
    "Spider-man",
    "Spirited Away",
    "Star Wars",
    "The Exorcist",
    "The Fast and the Furious",
    "The Godfather",
    "The Hobbit",
    "The Hunger Games",
    "The Lion King",
    "The Lord of the Rings",
    "The Martian",
    "The Matrix",
    "The Notebook",
    "The Omen",
    "The Shawshank Redemption",
    "The Shining",
    "The Silence of the Lambs",
    "The Sixth Sense",
    "The Terminator",
    "The Thing",
    "The Truman Show",
    "The Usual Suspects",
    "Titanic",
    "Top Gun",
    "Toy Story",
    "Transformers",
    "Twilight",
    "Twister",
    "Up",
    "Wall-E",
    "War of the Worlds",
    "Whiplash"
]